#!/bin/bash

# N0DE Environment Management System
# Consolidates and manages all environment configuration

# Load error handling library
source "/home/sol/n0de-deploy/lib/error-handler.sh"
init_error_handler "$(basename "$0")"

# Configuration
ENV_DIR="/home/sol/n0de-deploy"
TEMPLATE_FILE="$ENV_DIR/.env.production.template"
PRODUCTION_FILE="$ENV_DIR/.env.production"
DATABASE_FILE="$ENV_DIR/.env.database"
REDIS_FILE="$ENV_DIR/.env.redis"
MERGED_FILE="$ENV_DIR/.env.merged"
BACKUP_DIR="$ENV_DIR/env-backups"

# Environment validation rules
declare -A REQUIRED_VARS=(
    ["NODE_ENV"]="production"
    ["PORT"]="3001"
    ["DATABASE_URL"]="postgresql://"
    ["REDIS_URL"]="redis://"
    ["JWT_SECRET"]="minimum_32_chars"
)

declare -A OPTIONAL_VARS=(
    ["GITHUB_CLIENT_ID"]="OAuth GitHub integration"
    ["GOOGLE_CLIENT_ID"]="OAuth Google integration"  
    ["STRIPE_SECRET_KEY"]="Payment processing"
    ["RESEND_API_KEY"]="Email notifications"
    ["FRONTEND_URL"]="Frontend application URL"
    ["BACKEND_URL"]="Backend API URL"
)

# Create environment manager structure
init_env_manager() {
    log_info "Initializing environment manager"
    
    require_directory "$BACKUP_DIR" true "Environment backups directory"
    
    # Ensure template exists
    if [ ! -f "$TEMPLATE_FILE" ]; then
        create_production_template
    fi
    
    log_success "Environment manager initialized"
}

# Create comprehensive production template
create_production_template() {
    log_info "Creating comprehensive production environment template"
    
    cat > "$TEMPLATE_FILE" << 'EOF'
# N0DE Production Environment Configuration
# Copy this to .env.production and configure with your actual values

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================
NODE_ENV=production
PORT=3001
APP_NAME="N0DE Backend API"
API_VERSION="1.0.0"

# =============================================================================
# DATABASE CONFIGURATION (Auto-generated by db-setup.sh)
# =============================================================================
DATABASE_URL="postgresql://n0de_user:GENERATED_PASSWORD@localhost:5432/n0de_db"

# =============================================================================
# REDIS CONFIGURATION (Auto-generated by redis-setup.sh)  
# =============================================================================
REDIS_URL="redis://localhost:6379/1"

# =============================================================================
# AUTHENTICATION & SECURITY
# =============================================================================
# Generate with: openssl rand -base64 32
JWT_SECRET="CHANGE_THIS_TO_SECURE_32_CHAR_SECRET"
JWT_EXPIRES_IN="7d"

# Session configuration
SESSION_SECRET="CHANGE_THIS_TO_SECURE_SESSION_SECRET"

# =============================================================================
# OAUTH PROVIDERS (Configure for user authentication)
# =============================================================================

# GitHub OAuth (https://github.com/settings/developers)
GITHUB_CLIENT_ID="your_github_client_id"
GITHUB_CLIENT_SECRET="your_github_client_secret"

# Google OAuth (https://console.developers.google.com)
GOOGLE_CLIENT_ID="your_google_client_id"
GOOGLE_CLIENT_SECRET="your_google_client_secret"

# =============================================================================
# PAYMENT PROVIDERS
# =============================================================================

# Stripe (https://dashboard.stripe.com/apikeys)
STRIPE_SECRET_KEY="sk_live_your_stripe_secret_key"
STRIPE_PUBLISHABLE_KEY="pk_live_your_stripe_publishable_key"
STRIPE_WEBHOOK_SECRET="whsec_your_webhook_secret"

# Coinbase Commerce (https://commerce.coinbase.com/dashboard/settings)
COINBASE_API_KEY="your_coinbase_api_key"
COINBASE_WEBHOOK_SECRET="your_coinbase_webhook_secret"

# NOWPayments (https://account.nowpayments.io/settings/api-keys)
NOWPAYMENTS_API_KEY="your_nowpayments_api_key"
NOWPAYMENTS_WEBHOOK_SECRET="your_nowpayments_webhook_secret"

# =============================================================================
# EMAIL SERVICE
# =============================================================================

# Resend (https://resend.com/api-keys)
RESEND_API_KEY="re_your_resend_api_key"
FROM_EMAIL="support@n0de.pro"
REPLY_TO_EMAIL="noreply@n0de.pro"

# =============================================================================
# APPLICATION URLS
# =============================================================================
FRONTEND_URL="https://n0de.pro"
BACKEND_URL="https://your-server-domain-or-ip"
CALLBACK_URL="https://n0de.pro/auth/callback"

# API Documentation
SWAGGER_URL="https://your-server-domain-or-ip/docs"

# =============================================================================
# RATE LIMITING & PERFORMANCE
# =============================================================================
RATE_LIMIT_TTL=60
RATE_LIMIT_LIMIT=100
CORS_ORIGINS="https://n0de.pro,https://www.n0de.pro"

# =============================================================================
# LOGGING & MONITORING  
# =============================================================================
LOG_LEVEL="info"
LOG_FILE="/var/log/n0de/application.log"

# Sentry (Optional - for error tracking)
SENTRY_DSN=""

# =============================================================================
# FEATURE FLAGS
# =============================================================================
ENABLE_SWAGGER=false
ENABLE_CORS=true
ENABLE_HELMET=true
ENABLE_RATE_LIMITING=true

# =============================================================================
# DEVELOPMENT/DEBUG (Disable in production)
# =============================================================================
DEBUG=false
VERBOSE_LOGGING=false

# =============================================================================
# BACKUP & MAINTENANCE
# =============================================================================
BACKUP_RETENTION_DAYS=30
MAINTENANCE_MODE=false
MAINTENANCE_MESSAGE="System maintenance in progress"
EOF
    
    chmod 600 "$TEMPLATE_FILE"
    log_success "Production template created: $TEMPLATE_FILE"
}

# Backup current environment
backup_environment() {
    local backup_name="env-backup-$(date +%Y%m%d_%H%M%S)"
    local backup_path="$BACKUP_DIR/$backup_name"
    
    log_info "Creating environment backup: $backup_name"
    
    mkdir -p "$backup_path"
    
    # Backup all existing environment files
    for env_file in "$PRODUCTION_FILE" "$DATABASE_FILE" "$REDIS_FILE"; do
        if [ -f "$env_file" ]; then
            cp "$env_file" "$backup_path/"
            log_debug "Backed up: $(basename "$env_file")"
        fi
    done
    
    # Create backup manifest
    cat > "$backup_path/manifest.json" << EOF
{
    "timestamp": "$(date -Iseconds)",
    "hostname": "$(hostname)",
    "user": "$(whoami)",
    "files": [
        $(find "$backup_path" -name ".env*" -printf '"%f",\n' | sed '$ s/,$//')
    ]
}
EOF
    
    echo "$backup_path"
    log_success "Environment backup created: $backup_path"
}

# Merge environment files
merge_environment_files() {
    log_info "Merging environment files into unified configuration"
    
    # Start with production template
    if [ -f "$PRODUCTION_FILE" ]; then
        cp "$PRODUCTION_FILE" "$MERGED_FILE"
    else
        cp "$TEMPLATE_FILE" "$MERGED_FILE"
    fi
    
    # Merge database configuration
    if [ -f "$DATABASE_FILE" ]; then
        log_debug "Merging database configuration"
        
        # Extract DATABASE_URL from database file
        local db_url
        db_url=$(grep "^DATABASE_URL=" "$DATABASE_FILE" | cut -d'=' -f2- | tr -d '"')
        
        if [ -n "$db_url" ]; then
            # Replace DATABASE_URL in merged file
            sed -i "s|^DATABASE_URL=.*|DATABASE_URL=\"$db_url\"|" "$MERGED_FILE"
        fi
    fi
    
    # Merge Redis configuration
    if [ -f "$REDIS_FILE" ]; then
        log_debug "Merging Redis configuration"
        
        # Extract REDIS_URL from Redis file
        local redis_url
        redis_url=$(grep "^REDIS_URL=" "$REDIS_FILE" | cut -d'=' -f2- | tr -d '"')
        
        if [ -n "$redis_url" ]; then
            # Replace REDIS_URL in merged file
            sed -i "s|^REDIS_URL=.*|REDIS_URL=\"$redis_url\"|" "$MERGED_FILE"
        fi
    fi
    
    chmod 600 "$MERGED_FILE"
    log_success "Environment files merged: $MERGED_FILE"
}

# Validate environment configuration
validate_environment() {
    local env_file="${1:-$MERGED_FILE}"
    local validation_errors=0
    
    log_info "Validating environment configuration: $(basename "$env_file")"
    
    if [ ! -f "$env_file" ]; then
        log_error "Environment file not found: $env_file"
        return 1
    fi
    
    # Check required variables
    for var_name in "${!REQUIRED_VARS[@]}"; do
        local expected_pattern="${REQUIRED_VARS[$var_name]}"
        local var_value
        
        if grep -q "^${var_name}=" "$env_file"; then
            var_value=$(grep "^${var_name}=" "$env_file" | cut -d'=' -f2- | tr -d '"')
            
            case $expected_pattern in
                "minimum_32_chars")
                    if [ ${#var_value} -lt 32 ]; then
                        log_error "Variable $var_name must be at least 32 characters (current: ${#var_value})"
                        ((validation_errors++))
                    else
                        log_debug "✅ $var_name: Valid (${#var_value} chars)"
                    fi
                    ;;
                "postgresql://")
                    if [[ ! $var_value == postgresql://* ]]; then
                        log_error "Variable $var_name must be a PostgreSQL URL"
                        ((validation_errors++))
                    else
                        log_debug "✅ $var_name: Valid PostgreSQL URL"
                    fi
                    ;;
                "redis://")
                    if [[ ! $var_value == redis://* ]]; then
                        log_error "Variable $var_name must be a Redis URL"
                        ((validation_errors++))
                    else
                        log_debug "✅ $var_name: Valid Redis URL"
                    fi
                    ;;
                *)
                    if [ "$var_value" = "$expected_pattern" ]; then
                        log_debug "✅ $var_name: $var_value"
                    elif [ -n "$var_value" ]; then
                        log_debug "✅ $var_name: Configured"
                    else
                        log_error "Variable $var_name is empty"
                        ((validation_errors++))
                    fi
                    ;;
            esac
        else
            log_error "Required variable missing: $var_name"
            ((validation_errors++))
        fi
    done
    
    # Check for insecure defaults
    local insecure_defaults=(
        "CHANGE_THIS_TO_SECURE"
        "your_github_client"
        "your_google_client"
        "your_stripe_secret"
        "test-jwt-secret"
    )
    
    for default in "${insecure_defaults[@]}"; do
        if grep -q "$default" "$env_file"; then
            log_warning "Found insecure default value: $default"
            ((validation_errors++))
        fi
    done
    
    # Check file permissions
    local file_perms=$(stat -c "%a" "$env_file")
    if [ "$file_perms" != "600" ]; then
        log_error "Insecure file permissions: $file_perms (should be 600)"
        ((validation_errors++))
    fi
    
    if [ $validation_errors -eq 0 ]; then
        log_success "Environment validation passed"
        return 0
    else
        log_error "Environment validation failed with $validation_errors error(s)"
        return 1
    fi
}

# Generate secure secrets
generate_secrets() {
    log_info "Generating secure secrets"
    
    # Generate JWT secret
    local jwt_secret
    jwt_secret=$(openssl rand -base64 32)
    echo "JWT_SECRET=\"$jwt_secret\""
    
    # Generate session secret
    local session_secret
    session_secret=$(openssl rand -base64 32)
    echo "SESSION_SECRET=\"$session_secret\""
    
    # Generate webhook secrets
    local webhook_secret
    webhook_secret=$(openssl rand -hex 16)
    echo "COINBASE_WEBHOOK_SECRET=\"$webhook_secret\""
    
    webhook_secret=$(openssl rand -hex 16)
    echo "NOWPAYMENTS_WEBHOOK_SECRET=\"$webhook_secret\""
    
    log_success "Secure secrets generated"
}

# Interactive configuration wizard
run_configuration_wizard() {
    log_info "Starting environment configuration wizard"
    
    echo -e "${PURPLE}🧙 N0DE Environment Configuration Wizard${NC}"
    echo -e "${PURPLE}==========================================${NC}"
    echo ""
    
    # Backup current environment
    if [ -f "$PRODUCTION_FILE" ]; then
        echo -e "${YELLOW}Backing up current configuration...${NC}"
        backup_environment
        echo ""
    fi
    
    # Start with template
    cp "$TEMPLATE_FILE" "$PRODUCTION_FILE"
    
    echo -e "${BLUE}Configuring essential settings...${NC}"
    echo ""
    
    # JWT Secret
    echo -e "${YELLOW}🔐 JWT Secret Configuration${NC}"
    if confirm_action "Generate secure JWT secret automatically?" "y"; then
        local jwt_secret
        jwt_secret=$(openssl rand -base64 32)
        sed -i "s|^JWT_SECRET=.*|JWT_SECRET=\"$jwt_secret\"|" "$PRODUCTION_FILE"
        echo -e "${GREEN}✅ JWT secret configured${NC}"
    else
        echo "Please update JWT_SECRET manually in $PRODUCTION_FILE"
    fi
    echo ""
    
    # Database configuration
    echo -e "${YELLOW}🗄️  Database Configuration${NC}"
    if [ -f "$DATABASE_FILE" ]; then
        echo "Using existing database configuration from $DATABASE_FILE"
    else
        echo "⚠️  Database not configured. Run: ./scripts/db-setup.sh"
    fi
    echo ""
    
    # Redis configuration
    echo -e "${YELLOW}🔴 Redis Configuration${NC}"
    if [ -f "$REDIS_FILE" ]; then
        echo "Using existing Redis configuration from $REDIS_FILE"
    else
        echo "⚠️  Redis not configured. Run: ./scripts/redis-setup.sh"
    fi
    echo ""
    
    # Frontend URL
    echo -e "${YELLOW}🌐 Application URLs${NC}"
    read -p "Enter your server domain or IP (e.g., api.n0de.pro): " server_url
    if [ -n "$server_url" ]; then
        sed -i "s|BACKEND_URL=\".*\"|BACKEND_URL=\"https://$server_url\"|" "$PRODUCTION_FILE"
        sed -i "s|SWAGGER_URL=\".*\"|SWAGGER_URL=\"https://$server_url/docs\"|" "$PRODUCTION_FILE"
        echo -e "${GREEN}✅ Server URLs configured${NC}"
    fi
    echo ""
    
    # OAuth configuration
    echo -e "${YELLOW}🔑 OAuth Configuration (Optional)${NC}"
    if confirm_action "Configure GitHub OAuth?" "n"; then
        read -p "GitHub Client ID: " github_id
        read -s -p "GitHub Client Secret: " github_secret
        echo
        if [ -n "$github_id" ] && [ -n "$github_secret" ]; then
            sed -i "s|GITHUB_CLIENT_ID=\".*\"|GITHUB_CLIENT_ID=\"$github_id\"|" "$PRODUCTION_FILE"
            sed -i "s|GITHUB_CLIENT_SECRET=\".*\"|GITHUB_CLIENT_SECRET=\"$github_secret\"|" "$PRODUCTION_FILE"
            echo -e "${GREEN}✅ GitHub OAuth configured${NC}"
        fi
    fi
    echo ""
    
    # Merge with database/Redis files
    merge_environment_files
    cp "$MERGED_FILE" "$PRODUCTION_FILE"
    
    # Final validation
    echo -e "${BLUE}🔍 Validating configuration...${NC}"
    if validate_environment "$PRODUCTION_FILE"; then
        echo -e "${GREEN}🎉 Environment configuration completed successfully!${NC}"
        echo ""
        echo "Configuration file: $PRODUCTION_FILE"
        echo ""
        echo "Next steps:"
        echo "  1. Review and update remaining OAuth/payment settings if needed"
        echo "  2. Test the configuration: ./scripts/service-manager.sh start"
        echo "  3. Run the migration: ./scripts/complete-migration.sh"
    else
        echo -e "${RED}❌ Configuration validation failed${NC}"
        echo "Please review and fix the issues in $PRODUCTION_FILE"
        return 1
    fi
}

# Show environment status
show_environment_status() {
    echo -e "${PURPLE}📊 Environment Configuration Status${NC}"
    echo -e "${PURPLE}===================================${NC}"
    echo ""
    
    # Check file existence and permissions
    local files_checked=0
    local files_valid=0
    
    for file in "$PRODUCTION_FILE" "$DATABASE_FILE" "$REDIS_FILE"; do
        ((files_checked++))
        echo -n "$(basename "$file"): "
        
        if [ -f "$file" ]; then
            local perms=$(stat -c "%a" "$file")
            if [ "$perms" = "600" ]; then
                echo -e "${GREEN}✅ Exists (secure permissions)${NC}"
                ((files_valid++))
            else
                echo -e "${YELLOW}⚠️  Exists (insecure permissions: $perms)${NC}"
            fi
        else
            echo -e "${RED}❌ Missing${NC}"
        fi
    done
    
    echo ""
    echo "Files status: $files_valid/$files_checked valid"
    
    # Validate main production file if it exists
    if [ -f "$PRODUCTION_FILE" ]; then
        echo ""
        echo -e "${BLUE}🔍 Configuration Validation:${NC}"
        if validate_environment "$PRODUCTION_FILE" 2>/dev/null; then
            echo -e "${GREEN}✅ Production configuration is valid${NC}"
        else
            echo -e "${RED}❌ Production configuration has issues${NC}"
        fi
    fi
    
    # Show backup status
    echo ""
    echo -e "${BLUE}💾 Backup Status:${NC}"
    local backup_count=$(ls -1 "$BACKUP_DIR" 2>/dev/null | wc -l)
    echo "Available backups: $backup_count"
    if [ $backup_count -gt 0 ]; then
        echo "Latest backup: $(ls -1t "$BACKUP_DIR" | head -1)"
    fi
}

# Command line interface
main() {
    init_env_manager
    
    case "${1:-status}" in
        "init"|"setup")
            create_production_template
            echo "Environment template created. Run 'wizard' to configure."
            ;;
        "wizard"|"configure")
            run_configuration_wizard
            ;;
        "merge")
            backup_environment
            merge_environment_files
            echo "Environment files merged: $MERGED_FILE"
            ;;
        "validate")
            local file="${2:-$PRODUCTION_FILE}"
            validate_environment "$file"
            ;;
        "backup")
            backup_environment
            ;;
        "secrets")
            generate_secrets
            ;;
        "status"|"show")
            show_environment_status
            ;;
        "list-backups")
            echo "Environment backups:"
            ls -la "$BACKUP_DIR" 2>/dev/null || echo "No backups found"
            ;;
        "restore")
            local backup_name="$2"
            if [ -z "$backup_name" ]; then
                echo "Usage: $0 restore <backup-name>"
                echo "Available backups:"
                ls -1 "$BACKUP_DIR" 2>/dev/null || echo "No backups found"
                exit 1
            fi
            
            local backup_path="$BACKUP_DIR/$backup_name"
            if [ -d "$backup_path" ]; then
                backup_environment  # Backup current state first
                cp "$backup_path"/.env* "$ENV_DIR/" 2>/dev/null || true
                echo "Environment restored from: $backup_name"
            else
                echo "Backup not found: $backup_name"
                exit 1
            fi
            ;;
        *)
            echo "N0DE Environment Management System"
            echo ""
            echo "Usage: $0 [command]"
            echo ""
            echo "Commands:"
            echo "  status           - Show environment status (default)"
            echo "  init|setup       - Initialize environment template"
            echo "  wizard|configure - Run configuration wizard"
            echo "  merge            - Merge all environment files"
            echo "  validate [file]  - Validate environment configuration"
            echo "  backup           - Backup current environment"
            echo "  secrets          - Generate secure secrets"  
            echo "  list-backups     - List available backups"
            echo "  restore <name>   - Restore from backup"
            echo ""
            echo "Files:"
            echo "  .env.production.template - Configuration template"
            echo "  .env.production         - Main production config"
            echo "  .env.database           - Database connection (auto-generated)"
            echo "  .env.redis              - Redis connection (auto-generated)"
            ;;
    esac
}

main "$@"